language: cpp
sudo: false
dist: trusty
notifications:
  email: false

matrix:
  include:
    - os: linux
      compiler: gcc
      apt:
        packages:
          - gfortran-6
          - cmake
          - cmake-data

before_install:
  - export CC=/usr/bin/gcc-6
  - export FC=/usr/bin/gfortran-6
  - alias gfortran="/usr/bin/gfortran-6"
  - ./ci/install_python.sh
  - ./ci/install_esmf.sh
  - ./ci/install_pfunit.sh

install:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p build && cd build
  - cmake ..
  - make

before_script:
  - echo "before script"

script:
  - cd ${TRAVIS_BUILD_DIR}
  - ./build/prog
