language: cpp
sudo: required
dist: trusty
notifications:
  email: false

services:
  - docker

before_install:
  - docker version

install:
  - docker build -t lilac .

before_script:
  - docker images

script:
  - docker run -t lilac
