language: cpp
sudo: false
dist: trusty

matrix:
  include:
    - os: linux
      compiler: gcc
      apt:
        packages:
          - gfortran
          - cmake
          - cmake-data

before_install:
  - ./install_python.sh
  - ./install_esmf.sh
  - ./install_pfunit.sh

install:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p build && cd build
  - cmake ..
  - make

before_script:
  - echo "before script"

script:
  - cd ${TRAVIS_BUILD_DIR}
  - ./build/prog
