name: python testing on push and PR
#
# Run the python directory testing on push and pull request
#
on: [push, pull_request]

jobs:
  pytest:
     runs-on: ubuntu-latest
     steps:
        # Checkout the code
        - uses: actions/checkout@v2
        - uses: conda-incubator/setup-miniconda@v2
          with:
            activate-environment: ctsm_pylib
            environment-file: python/conda_env_ctsm_py.txt
            auto-activate-base: false
            channels: conda-forge
        - name: manage_exernals and LFS
          shell: bash -l {0}
          run: |
            git lfs install
            manage_externals/checkout_externals
        - name: Run python tests
          shell: bash -l {0}
          run: |
              cd python
              make test
        - name: Run pylint
          shell: bash -l {0}
          run: |
              cd python
              make lint
